### ISSUE TITLE
Changing profile pictures in Mastodon breaks them on the web-page

### ISSUE THREAD

**Issue by bluelhf** [ronilaukkarinen/finnish-mastodon-users#4]
## Issue Description
If, after an user is added to this list, they change their profile picture, the old file is deleted from the Mastodon instance, and the new profile picture is placed on a **different path.** This results in outdated profile pictures breaking.

### Possible solutions
I see four ways to go about solving this:
1. **Manually update the profile picture links each time someone changes their profile picture.**

    This is obviously not viable: maintenance needs would grow linearly with the amount of users in the list.

2. **Modify the system such as to make profile pictures synchronise with Mastodon instances automatically.**

    Setting this up might be difficult, and seems to be quite a lot of work to solve what is frankly quite a marginal problem. If a simple way to do this is found, (perhaps some sort of official embed provided at a static URL by the Mastodon instance itself?), I believe it should be implemented.

3. **Ignore the issue altogether.**

    This may cause the site's profile picture display to slowly break down over time, as people on the list make changes to their profile.

4. **Remove the profile picture display.**

    This would make the web-page a lot more dull, but at least it'd be consistently dull.

**Comment by rollecode** [comment]
I was thinking about that, but was kinda trusting the retention policy of the instances. I could have added the users so that their profile photos point to my instance as I do not clear up any old profile related media. But, as far as I know, old profile photos are not removed anyway (intentional or not), lucky for me (please see [the open issue about this](https://github.com/mastodon/mastodon/issues/9567)), so in my understanding there's no problem as long as the system does not clean itself in the future?

Option 4 is boring, because then I might just as well share the csv or do a simple csv to html generator (that was my idea first as well, but like I said it's boring).

I want this to be as static as possible for now. If you have ideas on how to make it more dynamic via scripts, I'm all ears. I'm not planning on implementing any oauth client as for now, because I haven't allocated much time for this project.
